In [20]:
import pandas as pd

In [21]:
df = pd.DataFrame({
    "Name":['Adi','Bobby','Candy','Dior','Ena'],
    "Age" : [20,21,19,22,20],
    "Marks":[85,90,75,95,88]
})

In [22]:
df.head(3)

    Name  Age  Marks
0    Adi   20     85
1  Bobby   21     90
2  Candy   19     75

In [23]:
df['Name']

0      Adi
1    Bobby
2    Candy
3     Dior
4      Ena
Name: Name, dtype: str

In [24]:
df.loc[df['Marks']>85]

    Name  Age  Marks
1  Bobby   21     90
3   Dior   22     95
4    Ena   20     88

In [25]:
df["Grade"] = ["B","A","C","A","B"]

In [26]:
df

    Name  Age  Marks Grade
0    Adi   20     85     B
1  Bobby   21     90     A
2  Candy   19     75     C
3   Dior   22     95     A
4    Ena   20     88     B

In [27]:
df.drop(["Age"],axis=1,inplace=True)

In [28]:
df

    Name  Marks Grade
0    Adi     85     B
1  Bobby     90     A
2  Candy     75     C
3   Dior     95     A
4    Ena     88     B