In [56]:
import pandas as pd

In [57]:
df = pd.DataFrame({
    "Name" : ["Sumit","Krish","Amit","Rahees","Prateek","Mayank","Aman","Rohit","Abhay","Sam"],
    "Maths" : [87,90,78,68,91,79,87,65,23,87],
    "Science" : [87,78,67,56,84,67,54,86,46,87],
    "English" : [98,89,77,67,87,98,67,49,56,78]
})

In [58]:
df

      Name  Maths  Science  English
0    Sumit     87       87       98
1    Krish     90       78       89
2     Amit     78       67       77
3   Rahees     68       56       67
4  Prateek     91       84       87
5   Mayank     79       67       98
6     Aman     87       54       67
7    Rohit     65       86       49
8    Abhay     23       46       56
9      Sam     87       87       78

In [59]:
print("average marks in maths :", df["Maths"].mean())

average marks in maths : 75.5

In [60]:
print("average marks in science :", df["Science"].mean())

average marks in science : 71.2

In [61]:
print("average marks in english :", df["English"].mean())

average marks in english : 76.6

In [62]:
df["Total"] =df["Maths"]+df["English"]+df["Science"]

In [63]:
df

      Name  Maths  Science  English  Total
0    Sumit     87       87       98    272
1    Krish     90       78       89    257
2     Amit     78       67       77    222
3   Rahees     68       56       67    191
4  Prateek     91       84       87    262
5   Mayank     79       67       98    244
6     Aman     87       54       67    208
7    Rohit     65       86       49    200
8    Abhay     23       46       56    125
9      Sam     87       87       78    252

In [64]:
df.loc[df["Total"]==df["Total"].max()]

    Name  Maths  Science  English  Total
0  Sumit     87       87       98    272

In [65]:
df["Result"] = (df["Total"]>= 150).map({True:"Pass",False:"Fail"})

In [66]:
df

      Name  Maths  Science  English  Total Result
0    Sumit     87       87       98    272   Pass
1    Krish     90       78       89    257   Pass
2     Amit     78       67       77    222   Pass
3   Rahees     68       56       67    191   Pass
4  Prateek     91       84       87    262   Pass
5   Mayank     79       67       98    244   Pass
6     Aman     87       54       67    208   Pass
7    Rohit     65       86       49    200   Pass
8    Abhay     23       46       56    125   Fail
9      Sam     87       87       78    252   Pass

In [67]:
df.sort_values(by="Total",ascending=False,inplace=True)

In [68]:
df

      Name  Maths  Science  English  Total Result
0    Sumit     87       87       98    272   Pass
4  Prateek     91       84       87    262   Pass
1    Krish     90       78       89    257   Pass
9      Sam     87       87       78    252   Pass
5   Mayank     79       67       98    244   Pass
2     Amit     78       67       77    222   Pass
6     Aman     87       54       67    208   Pass
7    Rohit     65       86       49    200   Pass
3   Rahees     68       56       67    191   Pass
8    Abhay     23       46       56    125   Fail