In [68]:
import numpy as np 
import pandas as pd

In [69]:
df = pd.read_csv("zomato.csv")
df

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...,...,...
7100,7100,7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,7101,7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,7102,7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,7103,7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,7104,7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [70]:
df.shape

(7105, 12)

In [71]:
df.head(10)

,Unnamed: 0.1,Unnamed: 0,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,0,0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,1,1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,2,2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,3,3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,4,4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
5,5,5,'@99,"Takeaway, Delivery",3.4,37,200.0,No,No,"Mughlai, Biryani, Chinese, North Indian",Whitefield,Whitefield
6,6,6,'@Italy,Casual Dining,4.1,305,700.0,Yes,No,Italian,Banashankari,Kumaraswamy Layout
7,7,7,'@North Parontha Hut,"Takeaway, Delivery",2.8,40,300.0,No,No,North Indian,Indiranagar,Old Airport Road
8,8,8,1000 B.C,Quick Bites,3.2,49,300.0,Yes,No,"Arabian, Sandwich, Rolls, Burger","Byresandra,Tavarekere,Madiwala",Koramangala 5th Block
9,9,9,100ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°C,Casual Dining,3.7,41,450.0,No,No,"Biryani, North Indian","Byresandra,Tavarekere,Madiwala",BTM

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7105 entries, 0 to 7104
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           7105 non-null   int64
 1   Unnamed: 0             7105 non-null   int64
 2   restaurant name        7105 non-null   str
 3   restaurant type        7105 non-null   str
 4   rate (out of 5)        7037 non-null   float64
 5   num of ratings         7105 non-null   int64
 6   avg cost (two people)  7048 non-null   float64
 7   online_order           7105 non-null   str
 8   table booking          7105 non-null   str
 9   cuisines type          7105 non-null   str
 10  area                   7105 non-null   str
 11  local address          7105 non-null   str
dtypes: float64(2), int64(3), str(7)
memory usage: 1.2 MB

In [73]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,rate (out of 5),num of ratings,avg cost (two people)
count,7105.000000,7105.000000,7037.000000,7105.000000,7048.000000
mean,3552.000000,3552.000000,3.514253,188.921042,540.286464
std,2051.181164,2051.181164,0.463249,592.171049,462.902305
min,0.000000,0.000000,1.800000,1.000000,40.000000
25%,1776.000000,1776.000000,3.200000,16.000000,300.000000
50%,3552.000000,3552.000000,3.500000,40.000000,400.000000
75%,5328.000000,5328.000000,3.800000,128.000000,600.000000
max,7104.000000,7104.000000,4.900000,16345.000000,6000.000000

In [74]:
df.isnull().sum()

Unnamed: 0.1              0
Unnamed: 0                0
restaurant name           0
restaurant type           0
rate (out of 5)          68
num of ratings            0
avg cost (two people)    57
online_order              0
table booking             0
cuisines type             0
area                      0
local address             0
dtype: int64

In [75]:
df[["Unnamed: 0.1","Unnamed: 0"]]

      Unnamed: 0.1  Unnamed: 0
0                0           0
1                1           1
2                2           2
3                3           3
4                4           4
...            ...         ...
7100          7100        7100
7101          7101        7101
7102          7102        7102
7103          7103        7103
7104          7104        7104

[7105 rows x 2 columns]

In [76]:
df = df.drop(["Unnamed: 0.1","Unnamed: 0"],axis=1)
df

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [77]:
df.duplicated().sum()

0

In [78]:
df["restaurant type"].unique()

<ArrowStringArray>
[                  'Quick Bites',                          'Cafe',
                 'Casual Dining',            'Takeaway, Delivery',
            'Bar, Casual Dining',                   'Fine Dining',
                           'Pub',            'Casual Dining, Bar',
                      'Delivery',                         'Kiosk',
                    'Food Court',                  'Microbrewery',
                           'Bar',                          'Mess',
                        'Bakery',                'Dessert Parlor',
                 'Beverage Shop',                    'Sweet Shop',
                         'Dhaba',             'Cafe, Quick Bites',
   'Microbrewery, Casual Dining', 'Dessert Parlor, Beverage Shop',
                   'Bar, Lounge',             'Quick Bites, Mess',
                    'Food Truck',                   'Lounge, Bar',
          'Cafe, Dessert Parlor',    'Quick Bites, Beverage Shop',
            'Pub, Casual Dining',             'Pub, Microbrewery',
       'Sweet Shop, Quick Bites',                  'Cafe, Bakery',
              'Fine Dining, Bar',                      'Bar, Pub',
           'Bakery, Quick Bites',         'Bakery, Beverage Shop',
        'Bakery, Dessert Parlor',                      'Takeaway',
                        'Lounge',          'Microbrewery, Lounge',
          'Lounge, Microbrewery',   'Casual Dining, Microbrewery',
            'Casual Dining, Pub',                  'Bakery, Cafe',
           'Casual Dining, Cafe',             'Microbrewery, Pub',
                     'Cafe, Bar',             'Quick Bites, Cafe',
           'Cafe, Casual Dining',                      'Pub, Bar',
   'Quick Bites, Dessert Parlor',   'Dessert Parlor, Quick Bites',
    'Beverage Shop, Quick Bites',       'Food Court, Quick Bites',
       'Quick Bites, Sweet Shop',         'Casual Dining, Lounge',
        'Dessert Parlor, Bakery',    'Dessert Parlor, Sweet Shop',
 'Beverage Shop, Dessert Parlor',                  'Cafe, Lounge',
    'Casual Dining, Quick Bites',                          'Club',
     'Food Court, Casual Dining',           'Quick Bites, Bakery',
         'Lounge, Casual Dining',    'Food Court, Dessert Parlor',
          'Dessert Parlor, Cafe',                  'Lounge, Cafe',
    'Dessert Parlor, Food Court',             'Microbrewery, Bar',
                 'Confectionery',           'Fine Dining, Lounge',
    'Casual Dining, Irani Cafee',     'Fine Dining, Microbrewery',
           'Beverage Shop, Cafe',                    'Bhojanalya',
     'Food Court, Beverage Shop',       'Quick Bites, Food Court',
     'Casual Dining, Sweet Shop',        'Quick Bites, Meat Shop',
           'Club, Casual Dining']
Length: 81, dtype: str

In [79]:

median_rating = round(df.groupby("restaurant type")["rate (out of 5)"].median(),1)
df["rate (out of 5)"] = df["rate (out of 5)"].fillna(
    df["restaurant type"].map(median_rating))

In [80]:
mean_cost = df.groupby("restaurant type")["avg cost (two people)"].mean()
df["avg cost (two people)"] = df["avg cost (two people)"].fillna(
    df["restaurant type"].map(median_rating))

In [81]:
df.head()

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur

In [82]:
df.isna().sum()

restaurant name          0
restaurant type          0
rate (out of 5)          0
num of ratings           0
avg cost (two people)    0
online_order             0
table booking            0
cuisines type            0
area                     0
local address            0
dtype: int64

In [83]:
df

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,#FeelTheROLL,Quick Bites,3.4,7,200.0,No,No,Fast Food,Bellandur,Bellandur
1,#L-81 Cafe,Quick Bites,3.9,48,400.0,Yes,No,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,#refuel,Cafe,3.7,37,400.0,Yes,No,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,'@ Biryani Central,Casual Dining,2.7,135,550.0,Yes,No,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,'@ The Bbq,Casual Dining,2.8,40,700.0,Yes,No,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,894,600.0,Yes,No,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,Yes,No,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,No,No,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,Yes,No,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,No,No,Fast Food,Bannerghatta Road,South Bangalore

In [84]:
df[["table booking"]].value_counts()

table booking
No               6361
Yes               744
Name: count, dtype: int64

In [85]:
df["table booking"] = df["table booking"].map({"Yes":1,"No":0})

In [86]:
df["online_order"] = df["online_order"].map({"Yes":1,"No":0})

In [87]:
df.describe()

,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking
count,7105.000000,7105.000000,7105.000000,7105.000000,7105.000000
mean,3.513357,188.921042,535.980591,0.524560,0.104715
std,0.461191,592.171049,463.521406,0.499432,0.306207
min,1.800000,1.000000,3.300000,0.000000,0.000000
25%,3.200000,16.000000,300.000000,0.000000,0.000000
50%,3.500000,40.000000,400.000000,1.000000,0.000000
75%,3.800000,128.000000,600.000000,1.000000,0.000000
max,4.900000,16345.000000,6000.000000,1.000000,1.000000

In [88]:
df["restaurant type"].unique()

<ArrowStringArray>
[                  'Quick Bites',                          'Cafe',
                 'Casual Dining',            'Takeaway, Delivery',
            'Bar, Casual Dining',                   'Fine Dining',
                           'Pub',            'Casual Dining, Bar',
                      'Delivery',                         'Kiosk',
                    'Food Court',                  'Microbrewery',
                           'Bar',                          'Mess',
                        'Bakery',                'Dessert Parlor',
                 'Beverage Shop',                    'Sweet Shop',
                         'Dhaba',             'Cafe, Quick Bites',
   'Microbrewery, Casual Dining', 'Dessert Parlor, Beverage Shop',
                   'Bar, Lounge',             'Quick Bites, Mess',
                    'Food Truck',                   'Lounge, Bar',
          'Cafe, Dessert Parlor',    'Quick Bites, Beverage Shop',
            'Pub, Casual Dining',             'Pub, Microbrewery',
       'Sweet Shop, Quick Bites',                  'Cafe, Bakery',
              'Fine Dining, Bar',                      'Bar, Pub',
           'Bakery, Quick Bites',         'Bakery, Beverage Shop',
        'Bakery, Dessert Parlor',                      'Takeaway',
                        'Lounge',          'Microbrewery, Lounge',
          'Lounge, Microbrewery',   'Casual Dining, Microbrewery',
            'Casual Dining, Pub',                  'Bakery, Cafe',
           'Casual Dining, Cafe',             'Microbrewery, Pub',
                     'Cafe, Bar',             'Quick Bites, Cafe',
           'Cafe, Casual Dining',                      'Pub, Bar',
   'Quick Bites, Dessert Parlor',   'Dessert Parlor, Quick Bites',
    'Beverage Shop, Quick Bites',       'Food Court, Quick Bites',
       'Quick Bites, Sweet Shop',         'Casual Dining, Lounge',
        'Dessert Parlor, Bakery',    'Dessert Parlor, Sweet Shop',
 'Beverage Shop, Dessert Parlor',                  'Cafe, Lounge',
    'Casual Dining, Quick Bites',                          'Club',
     'Food Court, Casual Dining',           'Quick Bites, Bakery',
         'Lounge, Casual Dining',    'Food Court, Dessert Parlor',
          'Dessert Parlor, Cafe',                  'Lounge, Cafe',
    'Dessert Parlor, Food Court',             'Microbrewery, Bar',
                 'Confectionery',           'Fine Dining, Lounge',
    'Casual Dining, Irani Cafee',     'Fine Dining, Microbrewery',
           'Beverage Shop, Cafe',                    'Bhojanalya',
     'Food Court, Beverage Shop',       'Quick Bites, Food Court',
     'Casual Dining, Sweet Shop',        'Quick Bites, Meat Shop',
           'Club, Casual Dining']
Length: 81, dtype: str

# checking outliers

In [89]:
q1 = df["avg cost (two people)"].quantile(0.25)
q3 = df["avg cost (two people)"].quantile(0.75)

iqr = q3-q1 

lower_bound = q1-1.5*iqr
upper_bound = q3 + 1.5*iqr 

print(lower_bound," - ",upper_bound)

-150.0  -  1050.0

In [90]:
num_outliers = ((df["avg cost (two people)"] <lower_bound )| (df["avg cost (two people)"]>upper_bound)).sum()

In [91]:
num_outliers

661

In [92]:
df["avg cost (two people)"] = df["avg cost (two people)"].clip(0,upper_bound)
df["avg cost (two people)"]

0       200.0
1       400.0
2       400.0
3       550.0
4       700.0
        ...
7100    600.0
7101    250.0
7102    350.0
7103    650.0
7104    200.0
Name: avg cost (two people), Length: 7105, dtype: float64

In [93]:
q1 = df["num of ratings"].quantile(0.25)
q3 = df["num of ratings"].quantile(0.75)

iqr = q3-q1 

lower_bound_rating = q1-1.5*iqr
upper_bound_rating = q3 + 1.5*iqr 

print(lower_bound_rating," - ",upper_bound_rating)

-152.0  -  296.0

In [94]:
df["num of ratings"] = df["num of ratings"].clip(0,upper_bound_rating)
df["num of ratings"]

0         7
1        48
2        37
3       135
4        40
       ...
7100    296
7101     68
7102     33
7103    191
7104      9
Name: num of ratings, Length: 7105, dtype: int64

In [95]:
df["restaurant name"].head(10)

0                            #FeelTheROLL
1                              #L-81 Cafe
2                                 #refuel
3                      '@ Biryani Central
4                              '@ The Bbq
5                                    '@99
6                                 '@Italy
7                    '@North Parontha Hut
8                                1000 B.C
9    100ÃÂÃÂÃÂÃÂÃÂÃÂÃÂÃÂ°C
Name: restaurant name, dtype: str

In [97]:
import codecs

def fix_text(name):
    
    fixed = name
    for _ in range(10):
        new_fixed = codecs.decode(fixed.encode("latin1"), "utf-8", "ignore")
        if new_fixed == fixed:
            break
        fixed = new_fixed
    return fixed

In [98]:
df["restaurant name"] = df["restaurant name"].apply(fix_text)
df["restaurant name"].head(10)

0            #FeelTheROLL
1              #L-81 Cafe
2                 #refuel
3      '@ Biryani Central
4              '@ The Bbq
5                    '@99
6                 '@Italy
7    '@North Parontha Hut
8                1000 B.C
9                    100C
Name: restaurant name, dtype: str

In [99]:
broken_names = df["restaurant name"].str.contains("Ã", na=False) 
df.loc[broken_names]["restaurant name"]

Series([], Name: restaurant name, dtype: str)

In [104]:
df["restaurant name"] = df["restaurant name"].apply(lambda x : x.lstrip("',@#"))

In [105]:
df["restaurant name"]

0                  FeelTheROLL
1                    L-81 Cafe
2                       refuel
3              Biryani Central
4                      The Bbq
                 ...
7100                    Zoey's
7101    ZOROY Luxury Chocolate
7102         Zu's Doner Kebaps
7103                     Zyara
7104                    Zyksha
Name: restaurant name, Length: 7105, dtype: str

In [106]:
# final df 
df

,restaurant name,restaurant type,rate (out of 5),num of ratings,avg cost (two people),online_order,table booking,cuisines type,area,local address
0,FeelTheROLL,Quick Bites,3.4,7,200.0,0,0,Fast Food,Bellandur,Bellandur
1,L-81 Cafe,Quick Bites,3.9,48,400.0,1,0,"Fast Food, Beverages","Byresandra,Tavarekere,Madiwala",HSR
2,refuel,Cafe,3.7,37,400.0,1,0,"Cafe, Beverages",Bannerghatta Road,Bannerghatta Road
3,Biryani Central,Casual Dining,2.7,135,550.0,1,0,"Biryani, Mughlai, Chinese",Marathahalli,Marathahalli
4,The Bbq,Casual Dining,2.8,40,700.0,1,0,"BBQ, Continental, North Indian, Chinese, Bever...",Bellandur,Bellandur
...,...,...,...,...,...,...,...,...,...,...
7100,Zoey's,Cafe,4.3,296,600.0,1,0,"Cafe, Italian, Continental, Burger",Bellandur,Sarjapur Road
7101,ZOROY Luxury Chocolate,Dessert Parlor,4.0,68,250.0,1,0,Desserts,Brigade Road,Church Street
7102,Zu's Doner Kebaps,"Takeaway, Delivery",3.7,33,350.0,0,0,"Turkish, Fast Food, Biryani, Chinese",Malleshwaram,RT Nagar
7103,Zyara,Casual Dining,3.8,191,650.0,1,0,"North Indian, Mughlai, Chinese",Kammanahalli,HBR Layout
7104,Zyksha,Food Truck,3.4,9,200.0,0,0,Fast Food,Bannerghatta Road,South Bangalore